build-job:       # This job runs in the build stage, which runs first.
  image: docker/compose:latest
  stage: build
  script:
    - echo "Building and running docker..."
    - DOMAIN=molde.idi.ntnu.no rootlesskit docker-compose up --build -d
    - echo "Build complete"
  only:
    - production
