build-job:       # This job runs in the build stage, which runs first.
  image: docker/compose:latest
  stage: build
  script:
    - echo "Building docker..."
    - DOMAIN=molde.idi.ntnu.no docker-compose up --build -d --force-recreate
    - echo "Build complete."
  only:
    - production