version: '3'

services:

  backend:
    container_name: backend_group_XXX
    build:
      context: backend/
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    networks:
      backend_bridge:
        ipv4_address: 10.90.0.4
        
  frontend:
    container_name: frontend_group_XXX
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      backend_bridge:
        ipv4_address: 10.90.0.5

  gateway:
    container_name: gateway_group_XXX
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      backend_bridge:
        ipv4_address: 10.90.0.6

networks:  
  backend_bridge:
    driver: bridge
    ipam:
        config:
          - subnet: 10.90.0.0/18