version: '3'

services:

  backend:
    container_name: backend_group_${GROUP_ID}
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - PRODCUTION=${PRODUCTION}
      - GROUP_ID=${GROUP_ID}
      - PORT_PREFIX=${PORT_PREFIX}
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUP_ID}.0.4
        
  frontend:
    container_name: frontend_group_${GROUP_ID}
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        - GROUP_ID=${GROUP_ID}
        - PORT_PREFIX=${PORT_PREFIX}
        - DOMAIN=${DOMAIN}
        - PROTOCOL=${PROTOCOL}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUP_ID}.0.5

  gateway:
    container_name: gateway_group_${GROUP_ID}
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - ${PORT_PREFIX}${GROUP_ID}:80
    environment:
      - GROUP_ID=${GROUP_ID}
      - PORT_PREFIX=${PORT_PREFIX}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUP_ID}.0.6

networks:  
  backend_bridge:
    driver: bridge
    ipam:
        config:
          - subnet: 10.${GROUP_ID}.0.0/18