# Generated by Django 3.2.4 on 2021-11-25 11:19

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_mfa_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_hash',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
