# Generated by Django 3.2.4 on 2021-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_mfa_hash_user_mfa_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
