# Generated by Django 3.2.7 on 2021-10-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='date',
            field=models.DateField(),
        ),
    ]
