# Generated by Django 3.2.7 on 2021-10-28 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
