# Generated by Django 3.2.7 on 2021-11-12 12:23

import apps.children.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_child_guardians'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.children.models.child_directory_path)),
                ('content_type', models.CharField(max_length=64)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_files', to='children.child')),
            ],
        ),
    ]
