# Generated by Django 3.2.4 on 2021-11-25 17:32

import apps.children.models
import apps.children.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_childfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childfile',
            name='file',
            field=models.FileField(upload_to=apps.children.models.child_directory_path, validators=[apps.children.validators.FileValidator(allowed_extensions='', allowed_mimetypes='', max_size=float("inf"))]),
        ),
    ]
