# Generated by Django 3.2.7 on 2021-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sender',
            field=models.TextField(),
        ),
    ]
