# Generated by Django 3.2.7 on 2021-11-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20211012_2245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_alter_offer_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.advert'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_contract', to=settings.AUTH_USER_MODEL)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
